---
# NAT instance
application_nat_instance: false
application_nat_out_interface: "{{ ansible_default_ipv4.interface }}"

# Deployment
application_project_name: tiny-notes-app
application_deploy_dir: /opt/tiny-notes-app
application_src_backend: "{{ playbook_dir }}/../../app/backend"
application_src_frontend: "{{ playbook_dir }}/../../app/frontend"

# Docker
application_docker_apt_arch: amd64
application_docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-compose-plugin
