---
database_mysql_packages:
  - mysql-server
  - python3-pymysql

database_mysql_service: mysql
database_mysql_socket: /run/mysqld/mysqld.sock

database_mysql_user_host: "%"

database_mysql_bind_address: "0.0.0.0"
database_mysql_config_file: /etc/mysql/mysql.conf.d/mysqld.cnf
