---
- name: Save iptables rules
  ansible.builtin.command: netfilter-persistent save
  become: true
  changed_when: false

- name: Restart application
  community.docker.docker_compose_v2:
    project_src: "{{ application_deploy_dir }}"
    state: restarted
  become: true
