---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: Install base packages
  ansible.builtin.apt:
    name: "{{ common_packages }}"
    state: present
  become: true

- name: Set the system timezone
  community.general.timezone:
    name: "{{ common_timezone }}"
  become: true
  when: common_timezone is not none
