---
- name: Configure NAT instance
  ansible.builtin.import_tasks: nat.yml
  when: nat_instance | default(false) | bool

- name: Install Docker
  ansible.builtin.import_tasks: docker.yml

- name: Deploy the application
  ansible.builtin.import_tasks: deploy.yml
